name: Create release
on:
  push:
    branches:
      - main

jobs:  
  bundle-and-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup node js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Bundle to zip
        run: |
          zip -r extension.zip src
      
      - name: Release zip
        run: |
          npm ci
          npm run release
        