name: Update versions in manifest
on:
  pull_request:
  merge_group:

jobs:
  update-manifest-version:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get version number
        uses: codfish/semantic-release-action@v3
        id: generate_version
        with:
          dry-run: true
          plugins: |
            [
              '@semantic-release/commit-analyzer',
              '@semantic-release/release-notes-generator',
              '@semantic-release/github',
            ]
      
      - name: Configuration GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://github-actions:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}
          
      - name: Setup node js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install dependencies
        run: |
          npm ci

      - name: Update versioning
        run: |
          npx dot-json@1 ./src/manifest.json version "${{ steps.generate_version.outputs.release-version }}"
          npx dot-json@1 package.json version "${{ steps.generate_version.outputs.release-version }}"

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(release): Bump up to v$(grep version package.json | awk -F \" '{print $4}')[skip ci]"
          git push origin HEAD